org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
unityStreamingAssets=
unityTemplateVersion=21
unityProjectPath=D:/CIT/Development/Projects/RemGloves-Software/RemGloveHand
unity.projectPath=D:/CIT/Development/Projects/RemGloves-Software/RemGloveHand
unity.debugSymbolLevel=none
unity.buildToolsVersion=36.0.0
unity.minSdkVersion=25
unity.targetSdkVersion=33
unity.compileSdkVersion=33
unity.applicationId=com.remglove.hand
unity.abiFilters=arm64-v8a
unity.versionCode=1
unity.versionName=0.1
unity.namespace=com.remglove.hand
unity.agpVersion=8.10.0
unity.androidSdkPath=C:/Program Files/Unity/Hub/Editor/6000.3.6f1/Editor/Data/PlaybackEngines/AndroidPlayer/SDK
unity.androidNdkPath=C:/Program Files/Unity/Hub/Editor/6000.3.6f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=C:/Program Files/Unity/Hub/Editor/6000.3.6f1/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK
unity.javaCompatabilityVersion=VERSION_17
unity.installInBuildFolder=false
android.useAndroidX=true
android.enableJetifier=true
android.bundle.includeNativeDebugMetadata=false
org.gradle.welcome=never