// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtDOM6dwRRgELX4KlcWS07ankXpBxU3cU',
    appId: '1:162508189162:web:cd89fcc4bf2e24563dd693',
    messagingSenderId: '162508189162',
    projectId: 'remgloves',
    authDomain: 'remgloves.firebaseapp.com',
    storageBucket: 'remgloves.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1cEqLx_-VU_G7zG3o9EL-LQjRX53CFlk',
    appId: '1:162508189162:android:47f6ddab267874cc3dd693',
    messagingSenderId: '162508189162',
    projectId: 'remgloves',
    storageBucket: 'remgloves.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-6gQxW7WxKynPi3BgmwWbxldETBQAriE',
    appId: '1:162508189162:ios:9add9f21a95e49c33dd693',
    messagingSenderId: '162508189162',
    projectId: 'remgloves',
    storageBucket: 'remgloves.firebasestorage.app',
    iosBundleId: 'com.example.remglovesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-6gQxW7WxKynPi3BgmwWbxldETBQAriE',
    appId: '1:162508189162:ios:9add9f21a95e49c33dd693',
    messagingSenderId: '162508189162',
    projectId: 'remgloves',
    storageBucket: 'remgloves.firebasestorage.app',
    iosBundleId: 'com.example.remglovesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtDOM6dwRRgELX4KlcWS07ankXpBxU3cU',
    appId: '1:162508189162:web:120839a501bbf0cd3dd693',
    messagingSenderId: '162508189162',
    projectId: 'remgloves',
    authDomain: 'remgloves.firebaseapp.com',
    storageBucket: 'remgloves.firebasestorage.app',
  );
}
